-- Create production tables with current schema.
-- Run in pgAdmin4 against Neon prod AFTER running drop_prod_tables.sql.
-- ts* tables are NOT included here.

CREATE TABLE IF NOT EXISTS tpl_players (
  pl_plid               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pl_name               VARCHAR(100)  NOT NULL UNIQUE,
  pl_nz_bridge_number   INTEGER       NOT NULL DEFAULT 0,
  pl_club               VARCHAR(100)  NOT NULL DEFAULT '',
  pl_rank               VARCHAR(100)  NOT NULL DEFAULT '',
  pl_grade              VARCHAR(50)   NOT NULL DEFAULT '',
  pl_rating             NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_a_points           NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_b_points           NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_c_points           NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_all_results        BOOLEAN       NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_pl_nz_bridge_number ON tpl_players (pl_nz_bridge_number) WHERE pl_nz_bridge_number > 0;

CREATE TABLE IF NOT EXISTS tse_sessions (
  se_seid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  se_date         DATE         NOT NULL,
  se_day_of_week  VARCHAR(10)  NOT NULL,
  se_scoring      VARCHAR(20)  NOT NULL,
  se_run_id    INTEGER      NOT NULL UNIQUE,
  se_name         VARCHAR(200) NOT NULL DEFAULT '',
  se_club         VARCHAR(100) NOT NULL DEFAULT '',
  se_tournament        VARCHAR(10)  NOT NULL DEFAULT '',
  se_event_type        VARCHAR(20)  NOT NULL DEFAULT '',
  se_partners_built    BOOLEAN      NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS tpa_partners (
  pa_paid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pa_plid1        INTEGER       NOT NULL,
  pa_plid2        INTEGER       NOT NULL,
  UNIQUE (pa_plid1, pa_plid2)
);

CREATE TABLE IF NOT EXISTS tre_results (
  re_reid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  re_seid         INTEGER,
  re_plid1        INTEGER,
  re_plid2        INTEGER,
  re_paid         INTEGER,
  re_percentage   NUMERIC(5,2) NOT NULL,
  re_vp           NUMERIC(5,2)
);
CREATE INDEX IF NOT EXISTS idx_tre_results_plid1 ON tre_results (re_plid1);
CREATE INDEX IF NOT EXISTS idx_tre_results_plid2 ON tre_results (re_plid2);
CREATE INDEX IF NOT EXISTS idx_tre_results_seid  ON tre_results (re_seid);
CREATE INDEX IF NOT EXISTS idx_tre_results_paid  ON tre_results (re_paid);

CREATE TABLE IF NOT EXISTS trk_ranks (
  rk_rkid  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rk_rank  VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tcl_clubs (
  cl_clid  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cl_club  VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tgr_grades (
  gr_grid  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gr_grade VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tet_event_types (
  et_etid      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  et_event_type VARCHAR(20) NOT NULL UNIQUE
);
INSERT INTO tet_event_types (et_event_type) VALUES
  ('pairs'), ('teams'), ('swiss_pairs'), ('swiss_teams')
ON CONFLICT (et_event_type) DO NOTHING;

CREATE TABLE IF NOT EXISTS ta1_player_stats (
  a1_a1id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  a1_plid        INTEGER      NOT NULL,
  a1_group       VARCHAR(3)   NOT NULL,
  a1_mp_sessions INTEGER      NOT NULL DEFAULT 0,
  a1_mp_avg_pct  NUMERIC(5,2) NOT NULL DEFAULT 0,
  a1_vp_sessions INTEGER      NOT NULL DEFAULT 0,
  a1_vp_avg_vp   NUMERIC(5,2) NOT NULL DEFAULT 0,
  UNIQUE (a1_plid, a1_group)
);
CREATE INDEX IF NOT EXISTS idx_ta1_player_stats_plid ON ta1_player_stats (a1_plid);

CREATE TABLE IF NOT EXISTS ta2_partner_stats (
  a2_a2id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  a2_plid1       INTEGER      NOT NULL,
  a2_plid2       INTEGER      NOT NULL,
  a2_group       VARCHAR(3)   NOT NULL,
  a2_mp_sessions INTEGER      NOT NULL DEFAULT 0,
  a2_mp_avg_pct  NUMERIC(5,2) NOT NULL DEFAULT 0,
  a2_vp_sessions INTEGER      NOT NULL DEFAULT 0,
  a2_vp_avg_vp   NUMERIC(5,2) NOT NULL DEFAULT 0,
  UNIQUE (a2_plid1, a2_plid2, a2_group)
);
CREATE INDEX IF NOT EXISTS idx_ta2_partner_stats_plids ON ta2_partner_stats (a2_plid1, a2_plid2);
