-- Bridge Results Tracker Schema
-- Naming convention: txx_name tables, xx_columnname columns, xx_yy_id foreign keys

CREATE TABLE IF NOT EXISTS tpl_players (
  pl_plid             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pl_name             VARCHAR(100) NOT NULL UNIQUE,
  pl_nz_bridge_number INTEGER      NOT NULL DEFAULT 0,  -- 0 = no number assigned
  pl_club             VARCHAR(100) NOT NULL DEFAULT '',
  pl_rank             VARCHAR(100) NOT NULL DEFAULT '',
  pl_grade            VARCHAR(50)  NOT NULL DEFAULT '',
  pl_rating           NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_a_points         NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_b_points         NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_c_points         NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_avg_percentage   NUMERIC(5,2) NOT NULL DEFAULT 0,  -- combined (all scoring types)
  pl_session_count    INTEGER      NOT NULL DEFAULT 0,  -- combined
  pl_mp_avg_percentage NUMERIC(5,2) NOT NULL DEFAULT 0,
  pl_mp_session_count  INTEGER      NOT NULL DEFAULT 0,
  pl_imp_avg_percentage NUMERIC(5,2) NOT NULL DEFAULT 0,
  pl_imp_session_count  INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tse_sessions (
  se_seid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  se_date         DATE NOT NULL,
  se_day_of_week  VARCHAR(10) NOT NULL,
  se_scoring      VARCHAR(20) NOT NULL,                 -- 'MP' or 'VP'
  se_source_id    INTEGER UNIQUE NOT NULL,
  se_session_type VARCHAR(20) NOT NULL DEFAULT 'club',  -- 'club' or 'online'
  se_name         VARCHAR(200) NOT NULL DEFAULT '',     -- scraped session label
  se_club         VARCHAR(100) NOT NULL DEFAULT '',
  se_tournament   VARCHAR(10)  NOT NULL DEFAULT '',
  se_event_type   VARCHAR(20)  NOT NULL DEFAULT ''      -- 'pairs' | 'teams' | 'swiss_pairs' | 'swiss_teams'
);


CREATE TABLE IF NOT EXISTS tpa_partners (
  pa_paid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pa_plid1        INTEGER NOT NULL,
  pa_plid2        INTEGER NOT NULL,
  pa_sessions     INTEGER NOT NULL DEFAULT 0,       -- combined
  pa_avg_pct      NUMERIC(5,2) NOT NULL DEFAULT 0,  -- combined
  pa_mp_sessions  INTEGER      NOT NULL DEFAULT 0,
  pa_mp_avg_pct   NUMERIC(5,2) NOT NULL DEFAULT 0,
  pa_imp_sessions INTEGER      NOT NULL DEFAULT 0,
  pa_imp_avg_pct  NUMERIC(5,2) NOT NULL DEFAULT 0,
  UNIQUE (pa_plid1, pa_plid2)
);

CREATE TABLE IF NOT EXISTS tre_results (
  re_reid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  re_seid         INTEGER,
  re_plid1        INTEGER,
  re_plid2        INTEGER,
  re_paid         INTEGER,
  re_percentage   NUMERIC(5,2) NOT NULL,  -- always a %, 0-100: PCT stored directly, VP converted via formula
  re_vp           NUMERIC(5,2),           -- raw VP score (NULL for non-VP sessions)
);

-- Partial unique indexes (exclude default/unset values)
CREATE UNIQUE INDEX IF NOT EXISTS uq_pl_nz_bridge_number ON tpl_players (pl_nz_bridge_number) WHERE pl_nz_bridge_number > 0;

-- trk_ranks: distinct player rank values for filtering
CREATE TABLE IF NOT EXISTS trk_ranks (
  rk_rkid  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rk_rank  VARCHAR(100) NOT NULL UNIQUE
);

-- tcl_clubs: distinct player club values for filtering
CREATE TABLE IF NOT EXISTS tcl_clubs (
  cl_clid  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cl_club  VARCHAR(100) NOT NULL UNIQUE
);

-- tgr_grades: distinct player grade values for filtering
CREATE TABLE IF NOT EXISTS tgr_grades (
  gr_grid  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gr_grade VARCHAR(50) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS ts9_nzb_results (
  s9_s9id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  s9_run_id      INTEGER       NOT NULL,
  s9_plid1       INTEGER       NOT NULL,  -- LEAST(plid_a, plid_b)
  s9_plid2       INTEGER       NOT NULL,  -- GREATEST(plid_a, plid_b)
  s9_date        DATE,
  s9_club        VARCHAR(100)  NOT NULL DEFAULT '',
  s9_event_name  VARCHAR(200)  NOT NULL DEFAULT '',
  s9_place       VARCHAR(10)   NOT NULL DEFAULT '',
  s9_score_value NUMERIC(10,2) NOT NULL DEFAULT 0,
  s9_score_type  VARCHAR(5)    NOT NULL DEFAULT '',  -- 'PCT' | 'VP'
  s9_tournament  VARCHAR(10)   NOT NULL DEFAULT '',
  s9_event_type  VARCHAR(20)   NOT NULL DEFAULT '',  -- 'pairs' | 'teams' | 'swiss_pairs' | 'swiss_teams'
  UNIQUE(s9_run_id, s9_plid1, s9_plid2)
);
CREATE INDEX IF NOT EXISTS idx_ts9_plid1  ON ts9_nzb_results (s9_plid1);
CREATE INDEX IF NOT EXISTS idx_ts9_plid2  ON ts9_nzb_results (s9_plid2);
CREATE INDEX IF NOT EXISTS idx_ts9_run_id ON ts9_nzb_results (s9_run_id);


-- tpr_partnership_results: unified pair results from NZ Bridge
CREATE TABLE IF NOT EXISTS tpr_partnership_results (
  pr_prid        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pr_plid1       INTEGER      NOT NULL,
  pr_plid2       INTEGER      NOT NULL,
  pr_date        DATE         NOT NULL,
  pr_score       NUMERIC(6,2) NOT NULL DEFAULT 0,
  pr_score_type  VARCHAR(10)  NOT NULL DEFAULT 'PCT',
  pr_source      VARCHAR(20)  NOT NULL,
  pr_event_name  VARCHAR(200) NOT NULL DEFAULT '',
  pr_place       VARCHAR(10)  NOT NULL DEFAULT '',
  pr_run_id      INTEGER
);
CREATE INDEX IF NOT EXISTS idx_tpr_plid1  ON tpr_partnership_results (pr_plid1);
CREATE INDEX IF NOT EXISTS idx_tpr_plid2  ON tpr_partnership_results (pr_plid2);
CREATE INDEX IF NOT EXISTS idx_tpr_pair   ON tpr_partnership_results (pr_plid1, pr_plid2);
CREATE INDEX IF NOT EXISTS idx_tpr_date   ON tpr_partnership_results (pr_date);
CREATE INDEX IF NOT EXISTS idx_tpr_source ON tpr_partnership_results (pr_source);

-- tlg_logging: required by nextjs-shared write_Logging
CREATE TABLE IF NOT EXISTS tlg_logging (
  lg_lgid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lg_datetime     TIMESTAMPTZ,
  lg_msg          TEXT,
  lg_functionname VARCHAR(128),
  lg_caller       VARCHAR(128),
  lg_severity     VARCHAR(4)
);
