-- Bridge Results Tracker Schema
-- Naming convention: txx_name tables, xx_columnname columns, xx_yy_id foreign keys

CREATE TABLE IF NOT EXISTS tpl_players (
  pl_plid             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pl_name             VARCHAR(100) NOT NULL UNIQUE,
  pl_nz_bridge_number INTEGER      NOT NULL DEFAULT 0,  -- 0 = no number assigned
  pl_club             VARCHAR(100) NOT NULL DEFAULT '',
  pl_rank             VARCHAR(100) NOT NULL DEFAULT '',
  pl_grade            VARCHAR(50)  NOT NULL DEFAULT '',
  pl_rating           NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_a_points         NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_b_points         NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_c_points         NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_last_updated     TIMESTAMP DEFAULT NOW(),
  pl_avg_percentage   NUMERIC(5,2) NOT NULL DEFAULT 0,  -- combined (all scoring types)
  pl_session_count    INTEGER      NOT NULL DEFAULT 0,  -- combined
  pl_mp_avg_percentage NUMERIC(5,2) NOT NULL DEFAULT 0,
  pl_mp_session_count  INTEGER      NOT NULL DEFAULT 0,
  pl_imp_avg_percentage NUMERIC(5,2) NOT NULL DEFAULT 0,
  pl_imp_session_count  INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tse_sessions (
  se_seid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  se_date         DATE NOT NULL,
  se_day_of_week  VARCHAR(10) NOT NULL,
  se_scoring      VARCHAR(20) NOT NULL,                 -- 'MP' or 'IMP'
  se_source_id    INTEGER UNIQUE NOT NULL,
  se_date_seq     INTEGER      NOT NULL DEFAULT 0,
  se_session_type VARCHAR(20) NOT NULL DEFAULT 'club'   -- 'club' or 'online'
);

CREATE TABLE IF NOT EXISTS tpa_partners (
  pa_paid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pa_plid1        INTEGER NOT NULL,
  pa_plid2        INTEGER NOT NULL,
  pa_sessions     INTEGER NOT NULL DEFAULT 0,       -- combined
  pa_avg_pct      NUMERIC(5,2) NOT NULL DEFAULT 0,  -- combined
  pa_mp_sessions  INTEGER      NOT NULL DEFAULT 0,
  pa_mp_avg_pct   NUMERIC(5,2) NOT NULL DEFAULT 0,
  pa_imp_sessions INTEGER      NOT NULL DEFAULT 0,
  pa_imp_avg_pct  NUMERIC(5,2) NOT NULL DEFAULT 0,
  pa_last_updated TIMESTAMP DEFAULT NOW(),
  UNIQUE (pa_plid1, pa_plid2)
);

CREATE TABLE IF NOT EXISTS tre_results (
  re_reid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  re_seid         INTEGER,
  re_plid         INTEGER,
  re_partner_plid INTEGER,
  re_pairid       INTEGER,
  re_percentage   DECIMAL(5,2) NOT NULL,
  re_imp_score    NUMERIC(8,1)           -- raw net IMP score; NULL for MP sessions
);

-- Partial unique indexes (exclude default/unset values)
CREATE UNIQUE INDEX IF NOT EXISTS uq_pl_nz_bridge_number ON tpl_players (pl_nz_bridge_number) WHERE pl_nz_bridge_number > 0;

-- trw_results_raw: staging table — raw pair names from AKBC before player ID resolution
CREATE TABLE IF NOT EXISTS trw_results_raw (
  rw_rwid       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rw_seid       INTEGER NOT NULL,
  rw_name1      VARCHAR(100) NOT NULL,  -- alphabetically first
  rw_name2      VARCHAR(100) NOT NULL,  -- alphabetically second
  rw_percentage DECIMAL(5,2) NOT NULL,
  rw_rank       INTEGER,               -- position in session (1 = best); IMP only
  rw_imp_score  NUMERIC(8,1)           -- net IMP score (e.g. +50.0, -23.5); IMP only
);

-- tam_players_ambiguous: players where nzbridge.co.nz returned multiple matches for review
CREATE TABLE IF NOT EXISTS tam_players_ambiguous (
  am_amid        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  am_search_name VARCHAR(100) NOT NULL DEFAULT '',
  am_nz_number   INTEGER      NOT NULL DEFAULT 0,
  am_nz_name     VARCHAR(100) NOT NULL DEFAULT '',
  am_club        VARCHAR(100) NOT NULL DEFAULT '',
  am_created     TIMESTAMP DEFAULT NOW()
);

-- tfl_fetch_log: tracks per-session fetch-results outcomes for admin review
CREATE TABLE IF NOT EXISTS tfl_fetch_log (
  fl_flid    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fl_seid    INTEGER NOT NULL,
  fl_run_at  TIMESTAMP DEFAULT NOW(),
  fl_pairs   INTEGER NOT NULL DEFAULT 0,
  fl_skipped BOOLEAN NOT NULL DEFAULT FALSE,
  fl_error   TEXT
);
CREATE INDEX IF NOT EXISTS idx_tfl_fetch_log_seid ON tfl_fetch_log (fl_seid);

-- tlg_logging: required by nextjs-shared write_Logging
CREATE TABLE IF NOT EXISTS tlg_logging (
  lg_lgid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lg_datetime     TIMESTAMPTZ,
  lg_msg          TEXT,
  lg_functionname VARCHAR(128),
  lg_caller       VARCHAR(128),
  lg_severity     VARCHAR(4)
);
