-- Bridge Results Tracker Schema
-- Naming convention: txx_name tables, xx_columnname columns, xx_yy_id foreign keys

CREATE TABLE IF NOT EXISTS tpl_players (
  pl_plid             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pl_name             VARCHAR(100) NOT NULL UNIQUE,
  pl_nz_bridge_number INTEGER      NOT NULL DEFAULT 0,  -- 0 = no number assigned
  pl_club             VARCHAR(100) NOT NULL DEFAULT '',
  pl_rank             VARCHAR(100) NOT NULL DEFAULT '',
  pl_grade            VARCHAR(50)  NOT NULL DEFAULT '',
  pl_rating           NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_a_points         NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_b_points         NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_c_points         NUMERIC(10,2) NOT NULL DEFAULT 0,
  pl_all_results        BOOLEAN      NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS tse_sessions (
  se_seid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  se_date         DATE NOT NULL,
  se_day_of_week  VARCHAR(10) NOT NULL,
  se_scoring      VARCHAR(20) NOT NULL,                 -- 'MP' or 'VP'
  se_run_id       INTEGER UNIQUE NOT NULL,
  se_name         VARCHAR(200) NOT NULL DEFAULT '',     -- scraped session label
  se_club         VARCHAR(100) NOT NULL DEFAULT '',
  se_tournament   VARCHAR(10)  NOT NULL DEFAULT '',
  se_event_type   VARCHAR(20)  NOT NULL DEFAULT '',     -- 'pairs' | 'teams' | 'swiss_pairs' | 'swiss_teams'
  se_is_summary   BOOLEAN NOT NULL DEFAULT false
);


CREATE TABLE IF NOT EXISTS tpa_partners (
  pa_paid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pa_plid1        INTEGER NOT NULL,
  pa_plid2        INTEGER NOT NULL,
  UNIQUE (pa_plid1, pa_plid2)
);

CREATE TABLE IF NOT EXISTS tre_results (
  re_reid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  re_seid         INTEGER,
  re_paid         INTEGER NOT NULL,
  re_percentage   NUMERIC(5,2),           -- NULL for VP sessions; percentage for MP sessions
  re_vp           NUMERIC(5,2)            -- raw VP score (NULL for non-VP sessions)
);

-- Partial unique indexes (exclude default/unset values)
CREATE UNIQUE INDEX IF NOT EXISTS uq_pl_nz_bridge_number ON tpl_players (pl_nz_bridge_number) WHERE pl_nz_bridge_number > 0;
CREATE INDEX IF NOT EXISTS idx_tre_re_paid ON tre_results (re_paid);

-- trk_ranks: distinct player rank values for filtering
CREATE TABLE IF NOT EXISTS trk_ranks (
  rk_rkid  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rk_rank  VARCHAR(100) NOT NULL UNIQUE
);

-- tcl_clubs: distinct player club values for filtering
CREATE TABLE IF NOT EXISTS tcl_clubs (
  cl_clid  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cl_club  VARCHAR(100) NOT NULL UNIQUE
);

-- tgr_grades: distinct player grade values for filtering
CREATE TABLE IF NOT EXISTS tgr_grades (
  gr_grid  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gr_grade VARCHAR(50) NOT NULL UNIQUE
);

-- tet_event_types: distinct event type values for filtering
CREATE TABLE IF NOT EXISTS tet_event_types (
  et_etid       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  et_event_type VARCHAR(50) NOT NULL UNIQUE
);

-- ta1_player_stats: pre-computed per-player stats by group (A/B/C/all)
CREATE TABLE IF NOT EXISTS ta1_player_stats (
  a1_a1id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  a1_plid       INTEGER      NOT NULL,
  a1_group      VARCHAR(3)   NOT NULL,
  a1_mp_sessions INTEGER     NOT NULL DEFAULT 0,
  a1_mp_avg_pct  NUMERIC(5,2) NOT NULL DEFAULT 0,
  a1_mp_stddev   NUMERIC(6,4),
  a1_vp_sessions INTEGER     NOT NULL DEFAULT 0,
  a1_vp_avg_vp   NUMERIC(5,2) NOT NULL DEFAULT 0,
  a1_vp_stddev   NUMERIC(6,4),
  UNIQUE (a1_plid, a1_group)
);
CREATE INDEX IF NOT EXISTS idx_ta1_plid  ON ta1_player_stats (a1_plid);
CREATE INDEX IF NOT EXISTS idx_ta1_group ON ta1_player_stats (a1_group);

-- ta2_partner_stats: pre-computed per-pair stats by group (A/B/C/all)
CREATE TABLE IF NOT EXISTS ta2_partner_stats (
  a2_a2id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  a2_paid       INTEGER      NOT NULL,
  a2_group      VARCHAR(3)   NOT NULL,
  a2_mp_sessions INTEGER     NOT NULL DEFAULT 0,
  a2_mp_avg_pct  NUMERIC(5,2) NOT NULL DEFAULT 0,
  a2_mp_stddev   NUMERIC(6,4),
  a2_vp_sessions INTEGER     NOT NULL DEFAULT 0,
  a2_vp_avg_vp   NUMERIC(5,2) NOT NULL DEFAULT 0,
  a2_vp_stddev   NUMERIC(6,4),
  UNIQUE (a2_paid, a2_group)
);
CREATE INDEX IF NOT EXISTS idx_ta2_paid   ON ta2_partner_stats (a2_paid);
CREATE INDEX IF NOT EXISTS idx_ta2_group  ON ta2_partner_stats (a2_group);

CREATE TABLE IF NOT EXISTS ts0_scraped (
  s0_s0id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  s0_run_id INTEGER NOT NULL DEFAULT 0,
  s0_source TEXT    NOT NULL DEFAULT 'club',
  s0_url    TEXT    NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS ts1_sessions (
  s1_s1id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  s1_run_id     INTEGER NOT NULL UNIQUE,
  s1_date       DATE,
  s1_club_id    INTEGER,
  s1_is_summary BOOLEAN NOT NULL DEFAULT false,
  s1_club       VARCHAR(100) NOT NULL DEFAULT '',
  s1_event_name VARCHAR(200) NOT NULL DEFAULT '',
  s1_score_type VARCHAR(5)   NOT NULL DEFAULT '',  -- 'PCT' | 'VP'
  s1_event_type VARCHAR(20)  NOT NULL DEFAULT '',  -- 'pairs' | 'teams'
  s1_tournament VARCHAR(10)  NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS ts2_results (
  s2_s2id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  s2_run_id      INTEGER       NOT NULL,
  s2_plid1       INTEGER       NOT NULL,  -- LEAST(plid_a, plid_b)
  s2_plid2       INTEGER       NOT NULL,  -- GREATEST(plid_a, plid_b)
  s2_score_value NUMERIC(10,2) NOT NULL DEFAULT 0,
  UNIQUE(s2_run_id, s2_plid1, s2_plid2)
);
CREATE INDEX IF NOT EXISTS idx_ts2_plid1  ON ts2_results (s2_plid1);
CREATE INDEX IF NOT EXISTS idx_ts2_plid2  ON ts2_results (s2_plid2);
CREATE INDEX IF NOT EXISTS idx_ts2_run_id ON ts2_results (s2_run_id);


-- xlg_logging: required by nextjs-shared write_Logging
CREATE TABLE IF NOT EXISTS xlg_logging (
  lg_lgid         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lg_severity     VARCHAR(4),
  lg_datetime     TIMESTAMPTZ,
  lg_msg          TEXT,
  lg_functionname VARCHAR(128),
  lg_caller       VARCHAR(128)
);
