-- Name: ta1_player_stats; Type: TABLE;
--

CREATE TABLE public.ta1_player_stats (
    a1_a1id integer NOT NULL,
    a1_plid integer NOT NULL,
    a1_group character varying(3) NOT NULL,
    a1_scoring character varying(5) NOT NULL,
    a1_sessions integer DEFAULT 0 NOT NULL,
    a1_avg numeric(5,2) DEFAULT 0 NOT NULL,
    a1_stddev numeric(5,2),
    a1_avg_rank integer,
    a1_group_total integer,
    a1_pct_rank numeric(5,4)
);

ALTER TABLE public.ta1_player_stats ALTER COLUMN a1_a1id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ta1_player_stats_a1_a1id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ta1_player_stats
    ADD CONSTRAINT ta1_player_stats_a1_plid_a1_group_a1_scoring_key UNIQUE (a1_plid, a1_group, a1_scoring);

ALTER TABLE ONLY public.ta1_player_stats
    ADD CONSTRAINT ta1_player_stats_pkey PRIMARY KEY (a1_a1id);

CREATE INDEX idx_ta1_player_stats_plid ON public.ta1_player_stats USING btree (a1_plid);

--
-- Name: ta2_partner_stats; Type: TABLE;
--

CREATE TABLE public.ta2_partner_stats (
    a2_a2id integer NOT NULL,
    a2_paid integer NOT NULL,
    a2_group character varying(3) NOT NULL,
    a2_scoring character varying(5) NOT NULL,
    a2_sessions integer DEFAULT 0 NOT NULL,
    a2_avg numeric(5,2) DEFAULT 0 NOT NULL,
    a2_stddev numeric(5,2),
    a2_avg_rank integer,
    a2_group_total integer
);

ALTER TABLE public.ta2_partner_stats ALTER COLUMN a2_a2id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ta2_partner_stats_a2_a2id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ta2_partner_stats
    ADD CONSTRAINT ta2_partner_stats_a2_paid_a2_group_a2_scoring_key UNIQUE (a2_paid, a2_group, a2_scoring);

ALTER TABLE ONLY public.ta2_partner_stats
    ADD CONSTRAINT ta2_partner_stats_pkey PRIMARY KEY (a2_a2id);

--
-- Name: tcl_clubs; Type: TABLE;
--

CREATE TABLE public.tcl_clubs (
    cl_clid integer NOT NULL,
    cl_club character varying(100) NOT NULL
);

ALTER TABLE public.tcl_clubs ALTER COLUMN cl_clid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tcl_clubs_cl_clid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tcl_clubs
    ADD CONSTRAINT tcl_clubs_cl_club_key UNIQUE (cl_club);

ALTER TABLE ONLY public.tcl_clubs
    ADD CONSTRAINT tcl_clubs_pkey PRIMARY KEY (cl_clid);

--
-- Name: tet_event_types; Type: TABLE;
--

CREATE TABLE public.tet_event_types (
    et_etid integer NOT NULL,
    et_event_type character varying NOT NULL
);

ALTER TABLE public.tet_event_types ALTER COLUMN et_etid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tet_event_types_et_etid_seq
    START WITH 5
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tet_event_types
    ADD CONSTRAINT tet_event_types_et_event_type_key UNIQUE (et_event_type);

ALTER TABLE ONLY public.tet_event_types
    ADD CONSTRAINT tet_event_types_pkey PRIMARY KEY (et_etid);

--
-- Name: tgr_grades; Type: TABLE;
--

CREATE TABLE public.tgr_grades (
    gr_grid integer NOT NULL,
    gr_grade character varying(50) NOT NULL
);

ALTER TABLE public.tgr_grades ALTER COLUMN gr_grid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tgr_grades_gr_grid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tgr_grades
    ADD CONSTRAINT tgr_grades_gr_grade_key UNIQUE (gr_grade);

ALTER TABLE ONLY public.tgr_grades
    ADD CONSTRAINT tgr_grades_pkey PRIMARY KEY (gr_grid);

--
-- Name: tpa_partners; Type: TABLE;
--

CREATE TABLE public.tpa_partners (
    pa_paid integer NOT NULL,
    pa_plid1 integer NOT NULL,
    pa_plid2 integer NOT NULL
);

ALTER TABLE public.tpa_partners ALTER COLUMN pa_paid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tpa_partners_pa_paid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tpa_partners
    ADD CONSTRAINT tpa_partners_pa_plid1_pa_plid2_key UNIQUE (pa_plid1, pa_plid2);

ALTER TABLE ONLY public.tpa_partners
    ADD CONSTRAINT tpa_partners_pkey PRIMARY KEY (pa_paid);

--
-- Name: tpip_pipelinelog; Type: TABLE;
--

CREATE TABLE public.tpip_pipelinelog (
    pip_pipid        integer NOT NULL,
    pip_run_id       integer DEFAULT 0 NOT NULL,
    pip_step         smallint NOT NULL,
    pip_sub_step     character varying(1) NOT NULL,
    pip_sub_sub      character varying(4),
    pip_step_name    character varying(64) DEFAULT ''::character varying NOT NULL,
    pip_input_table  character varying(64),
    pip_input_recs   integer DEFAULT 0 NOT NULL,
    pip_output_table character varying(64),
    pip_output_recs  integer DEFAULT 0 NOT NULL,
    pip_duration_ms  integer DEFAULT 0 NOT NULL,
    pip_created      timestamp DEFAULT now() NOT NULL
);

ALTER TABLE public.tpip_pipelinelog ALTER COLUMN pip_pipid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tpip_pipelinelog_pip_pipid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tpip_pipelinelog
    ADD CONSTRAINT tpip_pipelinelog_pkey PRIMARY KEY (pip_pipid);

--
-- Name: tpl_players; Type: TABLE;
--

CREATE TABLE public.tpl_players (
    pl_plid integer NOT NULL,
    pl_name character varying(100) NOT NULL,
    pl_nz_bridge_number integer DEFAULT 0 NOT NULL,
    pl_club character varying(100) DEFAULT ''::character varying NOT NULL,
    pl_rank character varying(100) DEFAULT ''::character varying NOT NULL,
    pl_grade character varying(50) DEFAULT ''::character varying NOT NULL,
    pl_rating numeric(10,2) DEFAULT 0 NOT NULL,
    pl_a_points numeric(10,2) DEFAULT 0 NOT NULL,
    pl_b_points numeric(10,2) DEFAULT 0 NOT NULL,
    pl_c_points numeric(10,2) DEFAULT 0 NOT NULL,
    pl_tracked boolean DEFAULT false NOT NULL
);

ALTER TABLE public.tpl_players ALTER COLUMN pl_plid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tpl_players_pl_plid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tpl_players
    ADD CONSTRAINT tpl_players_pkey PRIMARY KEY (pl_plid);

ALTER TABLE ONLY public.tpl_players
    ADD CONSTRAINT tpl_players_pl_name_key UNIQUE (pl_name);

CREATE UNIQUE INDEX uq_pl_nz_bridge_number ON public.tpl_players USING btree (pl_nz_bridge_number) WHERE (pl_nz_bridge_number > 0);

--
-- Name: tre_results; Type: TABLE;
--

CREATE TABLE public.tre_results (
    re_reid integer NOT NULL,
    re_seid integer,
    re_paid integer NOT NULL,
    re_score numeric(5,2)
);

ALTER TABLE public.tre_results ALTER COLUMN re_reid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tre_results_re_reid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tre_results
    ADD CONSTRAINT tre_results_pkey PRIMARY KEY (re_reid);

--
-- Name: trk_ranks; Type: TABLE;
--

CREATE TABLE public.trk_ranks (
    rk_rkid integer NOT NULL,
    rk_rank character varying(100) NOT NULL
);

ALTER TABLE public.trk_ranks ALTER COLUMN rk_rkid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trk_ranks_rk_rkid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.trk_ranks
    ADD CONSTRAINT trk_ranks_pkey PRIMARY KEY (rk_rkid);

ALTER TABLE ONLY public.trk_ranks
    ADD CONSTRAINT trk_ranks_rk_rank_key UNIQUE (rk_rank);

--
-- Name: ts0_scraped; Type: TABLE;
--

CREATE TABLE public.ts0_scraped (
    s0_s0id integer NOT NULL,
    s0_run_id integer DEFAULT 0 NOT NULL,
    s0_url text DEFAULT ''::text NOT NULL,
    s0_source text DEFAULT 'club'::text NOT NULL
);

ALTER TABLE public.ts0_scraped ALTER COLUMN s0_s0id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ts0_scraped_s0_s0id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ts0_scraped
    ADD CONSTRAINT ts0_scraped_pkey PRIMARY KEY (s0_s0id);

--
-- Name: ts1_sessions; Type: TABLE;
--

CREATE TABLE public.ts1_sessions (
    s1_s1id integer NOT NULL,
    s1_run_id integer NOT NULL,
    s1_date date,
    s1_club_id integer,
    s1_is_summary boolean DEFAULT false NOT NULL,
    s1_club character varying(100) DEFAULT ''::character varying NOT NULL,
    s1_event_name character varying(200) DEFAULT ''::character varying NOT NULL,
    s1_score_type character varying(5) DEFAULT ''::character varying NOT NULL,
    s1_event_type character varying(20) DEFAULT ''::character varying NOT NULL,
    s1_tournament character varying(10) DEFAULT ''::character varying NOT NULL
);

ALTER TABLE public.ts1_sessions ALTER COLUMN s1_s1id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ts1_sessions_s1_s1id_seq
    START WITH 2452
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ts1_sessions
    ADD CONSTRAINT ts10_nzb_missing_sessions_pkey PRIMARY KEY (s1_s1id);

ALTER TABLE ONLY public.ts1_sessions
    ADD CONSTRAINT ts10_nzb_missing_sessions_s10_run_id_key UNIQUE (s1_run_id);

--
-- Name: ts2_results; Type: TABLE;
--

CREATE TABLE public.ts2_results (
    s2_s2id integer NOT NULL,
    s2_run_id integer NOT NULL,
    s2_plid1 integer NOT NULL,
    s2_plid2 integer NOT NULL,
    s2_score_value numeric(10,2) DEFAULT 0 NOT NULL
);

ALTER TABLE public.ts2_results ALTER COLUMN s2_s2id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ts2_results_s2_s2id_seq
    START WITH 65909
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ts2_results
    ADD CONSTRAINT ts9_nzb_results_pkey PRIMARY KEY (s2_s2id);

ALTER TABLE ONLY public.ts2_results
    ADD CONSTRAINT ts9_nzb_results_s9_run_id_s9_plid1_s9_plid2_key UNIQUE (s2_run_id, s2_plid1, s2_plid2);

--
-- Name: tse_sessions; Type: TABLE;
--

CREATE TABLE public.tse_sessions (
    se_seid integer NOT NULL,
    se_date date NOT NULL,
    se_day_of_week character varying(10) NOT NULL,
    se_scoring character varying(20) NOT NULL,
    se_run_id integer NOT NULL,
    se_name character varying(200) DEFAULT ''::character varying NOT NULL,
    se_club character varying(100) DEFAULT ''::character varying NOT NULL,
    se_tournament character varying(10) DEFAULT ''::character varying NOT NULL,
    se_event_type character varying(20) DEFAULT ''::character varying NOT NULL,
    se_is_summary boolean
);

ALTER TABLE public.tse_sessions ALTER COLUMN se_seid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tse_sessions_se_seid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tse_sessions
    ADD CONSTRAINT tse_sessions_pkey PRIMARY KEY (se_seid);

ALTER TABLE ONLY public.tse_sessions
    ADD CONSTRAINT tse_sessions_se_source_id_key UNIQUE (se_run_id);

--
-- Name: xlg_logging; Type: TABLE;
--

CREATE TABLE public.xlg_logging (
    lg_lgid integer NOT NULL,
    lg_severity character(1),
    lg_caller character varying DEFAULT ''::character varying,
    lg_functionname character varying NOT NULL,
    lg_msg character varying NOT NULL,
    lg_datetime timestamp with time zone NOT NULL
);

ALTER TABLE public.xlg_logging ALTER COLUMN lg_lgid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xlg_logging_lg_lgid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.xlg_logging
    ADD CONSTRAINT xlg_logging_pkey PRIMARY KEY (lg_lgid);
